# The west manifest file for NCS Bare Metal

manifest:
  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: nrf
      repo-path: sdk-nrf
      revision: aa634ef1941514771316b2dabe4a4c1e768ffaec
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - dragoon
          - hal_nordic
          - lz4
          - mbedtls
          - mcuboot
          - memfault-firmware-sdk
          - nrfxlib
          - picolibc
          - oberon-psa-crypto
          - qcbor
          - segger
          - tinycrypt
          - zephyr
          - cmock
          - zcbor
    - name: sdk-nrf-bm-internal
      path: nrf-bm-internal
      revision: 2086b4bb5ee2cc68b824fe5ecd4e2461987e4c5c
      groups:
        - nrf-bm-internal
    - name: fatfs
      remote: zephyr
      path: fatfs
      revision: 42c2d6ee77e108d2a6d05e862ef0be23511db204

  self:
    path: nrf-bm
